# Generated by Django 3.2.3 on 2021-05-22 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='kebab_name',
            field=models.CharField(default='o', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
