version: '3.3'

services: 
    app:
        build:
            context: .
        volumes:
            - static_data:/vol/web
        env_file:
            secrets.env

    proxy:
        build:
            context: ./proxy
        volumes:
            - static_data:/vol/static
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - app

# Create the shared volume
volumes:
    static_data: